flaskr/models/product.py
from sqlalchemy import (
    Column, Integer, String, 
    Text, Float
)
from . import db, commit_to_db


class Product(db.Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text(1000), nullable=False)
    price = Column(Float, nullable=False, default=0)

    def add(self):
        db.session.add(self)
        commit_to_db()

    def update(self):
        commit_to_db()
    
    def delete(self):
        db.session.delete(self)
        commit_to_db()
    
    def search(search_term):
       return Product.query.filter_by(name=search_term)
       
    def get(id):
        return Product.query.get(id)
    
    def get_all():
        return Product.query.all()

    

flaskr/models/product/__init__.py
from sqlalchemy import (
    Column, Integer, String, 
    Text, Float
)
from flaskr.models import db, MyModel


class Product(db.Model, MyModel):
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text(1000), nullable=False)
    price = Column(Float, nullable=False, default=0)
    sold_products = db.relationship(
        'SoldProduct',
        backref='product',
        lazy=True, 
        cascade='all, delete-orphan'
    )
    
    def search(search_term):
        return Product.query.filter_by(name=search_term).first()
       
    def get(id):
        return Product.query.get(id)
    
    def get_all():
        return Product.query.all()

    @property
    def request(self):
        from .request import ProductRequest
        return ProductRequest(self)

flaskr/models/receipt/__init__.py
from sqlalchemy import (
    Column, Integer, String, 
    Text, Float, ForeignKey
)
from flaskr.models import db, MyModel, commit_to_db


class Receipt(db.Model, MyModel):
    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey('customer.id'), nullable=False)
    sold_products = db.relationship(
        'SoldProduct',
        backref='receipt',
        lazy=True,
        cascade='all, delete-orphan'
    )

    def search(search_term):
        search_result = Receipt.query.filter_by(name=search_term).first()
        return search_result
    
    def get(id):
        return Receipt.query.get(id)

    def get_all():
        return Receipt.query.all()
    
    @property
    def request(self):
        from .request import ReceiptRequest
        return ReceiptRequest(self)


class SoldProduct(db.Model, MyModel):
    id = Column(Integer, primary_key=True)
    receipt_id = Column(Integer, ForeignKey('receipt.id'), nullable=False)
    product_id = Column(Integer, ForeignKey('product.id'), nullable=False)
    quantity = Column(Integer)
    total =  Column(Float)
    
    def search_receipt(search_term):
        search_result = SoldProduct.query.filter_by(receipt_id=search_term).all()
        return search_result
    
    def delete_product(receipt_id, product_id):
        search_receipt = SoldProduct.query.filter_by(receipt_id=receipt_id).all()
        for product in search_receipt:
            if product.product.id == product_id:
                product.delete()

    def get(id):
        return SoldProduct.query.filter_by(id=id).first()

flaskr/views/home.py
from flask import (
    Blueprint, render_template
)

bp = Blueprint('home', __name__)


@bp.route('/')
def home():
    return render_template(
        'home/home.html'
    )

flaskr/views/product.py
from flask import (
    Blueprint, render_template, request, 
    redirect, url_for, flash
)
from flaskr.models.product import Product 
from . import get_form
bp = Blueprint('product', __name__, url_prefix='/product')


product_heads = {
    'name': 'name',
    'description': 'description',
    'price': 'price',
}


@bp.route('/products')
def products():
    products = Product.get_all()

    return render_template(
        'product/products.html',
        products=products,
        heads=product_heads
    )


@bp.route('/add', methods=("GET", "POST"))
def add():
    form = get_form(product_heads)
    if request.method == "POST":
        product = Product(
            name=form["name"],
            description=form["description"],
            price=form['price']
        )
        error = product.request.add()
        if not error: 
            return redirect(
                url_for('product.products')
            )
        flash(error)

    return render_template(
        'product/add.html',
        product_heads=product_heads
    )


@bp.route('/update/<int:product_id>', methods=("GET", "POST"))
def update(product_id):
    product = Product.get(product_id)
    if request.method == 'POST':
        error = product.request.update()
        if not error:
            return redirect(
                url_for('product.products')
            )

        flash(error)

    return render_template(
        'product/update.html',
        product=product, 
        heads=product_heads
    )


@bp.route('/delete/<int:product_id>', methods=("GET", "POST"))
def delete(product_id):
    product = Product.get(product_id)
    product.delete()

    return redirect(url_for('product.products'))




    

flaskr/views/receipt.py
from flask import (
    Blueprint, render_template, request, 
    redirect, url_for, flash
)

from . import get_form
from flaskr.models.receipt import Receipt, SoldProduct
from flaskr.models.customer import Customer
from flaskr.models.product import Product

bp = Blueprint('receipt', __name__, url_prefix='/receipt')


receipt_customer_heads = [
    'name',
    'address',
    'email'
]

product_heads = [
    'name',
    'description',
    'price',
    'total'
]

product_input = [
    'name',
    'quantity',
    'id_product'
    ]
quantity_input = ['quantity']


@bp.route('/receipts')
def receipts():
    receipts = Receipt.get_all()
    
    return render_template(
        'receipt/receipts.html',
        receipts=receipts,
        heads=receipt_customer_heads,
    )


@bp.route('/add', methods=('GET', 'POST'))
def add():
    receipt = None
    form = get_form(receipt_customer_heads)
    if request.method == 'POST':
        customer = Customer.search(form['name'])
        if customer:
            receipt = Receipt(
                customer_id=customer.id
            )
            receipt.add()
            return redirect(
                url_for('receipt.update', receipt_id=receipt.id )
               )

    return render_template(
        'receipt/add.html',
        receipt=receipt,
        heads=receipt_customer_heads,
        product_heads=product_heads
    )


@bp.route('/update/<int:receipt_id>', methods=('GET', 'POST'))
def update(receipt_id):
    error = "Product already selected"
    error_blank = "Cant submit empty fields"
    product = None
    receipt = Receipt.get(receipt_id)
    sold_products = SoldProduct.search_receipt(receipt_id)
    if request.method == 'POST':
        form = get_form(product_input)
        product = Product.search(form['name'])
        if product:
            for sold in sold_products:
                if sold.product.id == product.id:
                    flash(error)
                    return redirect(
                        url_for('receipt.update', receipt_id=receipt.id)
                    )
            sold_product = SoldProduct(product_id=product.id, receipt_id=receipt.id)
            sold_product.quantity = 1
            sold_product.total = product.price
            sold_product.add()
            sold_products = SoldProduct.search_receipt(receipt_id)
        else:
            if form['name'] == 'Product':
                flash(error_blank)
                return redirect(
                            url_for('receipt.update', receipt_id=receipt.id)
                        )
            else:
                add_quantity(form['quantity'], form['id_product'])
                sold_products = SoldProduct.search_receipt(receipt_id)
    receipt_total = get_receipt_total(receipt_id)

    
    return render_template(
        'receipt/update.html',
        product=product,
        customer=None,
        receipt=receipt,
        heads=receipt_customer_heads,
        product_heads=product_heads,
        sold_products=sold_products, 
        receipt_total=receipt_total
    )


@bp.route('/delete/<int:receipt_id>/<int:product_id>', methods=("GET", "POST"))
def delete_product(receipt_id ,product_id):
    
    SoldProduct.delete_product(receipt_id, product_id)

    return redirect(url_for('receipt.update', receipt_id=receipt_id))

@bp.route('/delete/<int:receipt_id>', methods=("GET", "POST"))
def delete_receipt(receipt_id):
    receipt = Receipt.get(receipt_id)
    receipt.delete()

    return redirect(url_for('receipt.receipts', receipt_id=receipt_id))


def add_quantity(quantity ,sold_product_id):
    product = SoldProduct.get(sold_product_id)
    product.quantity = quantity
    product_price = product.product.price
    product.total = product_price * int(quantity)
    product.update()


def get_receipt_total(receipt_id):
    receipts = SoldProduct.search_receipt(receipt_id)
    total = 0
    for receipt in receipts:
        total += receipt.total

    return total

flaskr/templates/receipt/add.html
{% extends 'base.html' %}

{% block content %}
<div class="main-container">
    <div class="receipt">
            <div class="client-info">
            {% include 'receipt/customer-info.html' %}
            </div>

        <div class="receipt-product">
            {% include 'receipt/products.html' %}
        </div>
    </div>

</div>

{% endblock %}

flaskr/templates/receipt/client-table.html
<table class="table-client-receipt">
    <tr>
    {% for head in heads %}
        <th>
           {{ head }}
        </th>
    {% endfor %}
    </tr>
    <tr>
    <form method="post">
        {% for head in heads %}
        {% if customer != None %}
        <td class="client-info-block">
            <input type="text" name="{{ head }}" id="{{ head }}" value="{{ customer[head] }}">
        </td>
        {% else %}
        <td class="client-info-block">
            <input type="text" name="{{ head }}" id="{{ head }}">
        </td>
        {% endif %}
        {% endfor %}
        <input type="submit" class="submit-btn">
    </form>
    </tr>
</table>

flaskr/templates/receipt/customer-info.html
<table class="table-client-receipt">
    <tr>
    {% for head in heads %}
        <th>
           {{ head }}
        </th>
    {% endfor %}
    </tr>
    <tr>
    {% if customer != None %}
    <form method="post">
        {% for head in heads %}
        {% if receipt != None %}
        <td class="client-info-block">
            <input type="text" name="{{ head }}" id="{{ head }}" value="{{ receipt.author[head] }}">
        </td>
        {% else %}
        <td class="client-info-block">
            <input type="text" name="{{ head }}" id="{{ head }}">
        </td>
        {% endif %}
        {% endfor %}
        <input type="submit" class="submit-btn">
    </form>
    {% endif %}
    </tr>
    <tr>
        {% if receipt != None %}
        {% for head in heads %}
        <td>
            <p>{{ receipt.author[head] }}</p>
        </td>
        {% endfor %}
        {% endif %}
    </tr>
</table>

flaskr/templates/receipt/products.html
<div class='receipt-search-product'>
    <form method="post">
        <input type="text" name="name" id="name" value="Product">
        <input type="submit" name="submit-product" class="submit-btn">
    </form>
    <div class="product-display">
        {% include 'receipt/table-products.html' %}
    </div>
</div>

flaskr/templates/receipt/receipts.html
{% extends 'base.html' %}


{% block title %}
<h1>Products</h1>
{% endblock %}

{% block content %}
<div class="title-container">
    <h1 class="title">Products</h1>
</div>
<table class="products">
    <tr>
        <th>Name</th>
        <th>id</th>
      </tr>
    {% for receipt in receipts %}
    <tr>
        <td>
            {{ receipt.author.name }}
        </td>
        <td>
            {{ receipt.id }}
        </td>
        <td>
            <a href="{{ url_for('receipt.update', receipt_id=receipt.id, refresh=True) }}">Update</a>
        </td>
        <td>
            <a href="{{ url_for('receipt.delete_receipt', receipt_id=receipt.id) }}">❌</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

flaskr/templates/receipt/table-products.html
<table class="products-receipt">
    <tr>
        <th>
            Quantity
        </th>
    {% for head in product_heads %}
       <th class="product-box">
            {{ head }}
        </th>
    {% endfor %}
    </tr>
    {% if sold_products != None %}
    {% for sold_product in sold_products %}
    <tr>
        <td class="td-quantity">
            <form method="post">
                <input type="number" name="quantity" class="quantity-input" value="{{ sold_product.quantity }}">
                <input type="number" name="id_product" class="id_product" value="{{ sold_product.id }}">
                <input type="submit" name="submit-quantity" class="submit-quantity" value="Add">
            </form>
        </td>
        {% for head in product_heads %}
        {% if head != quantity %}
        <td class="td-{{head}}">
            {% if head == 'total' %}
                {{ sold_product.total }}
            {% endif %}
            {{ sold_product.product[head] }}
        </td>
        {% endif %}
        {% endfor %}
        <td class="td-delete">
            <a href="{{ url_for('receipt.delete_product', receipt_id=receipt.id, product_id=sold_product.product.id) }}">❌</a>
        </td>
    </tr>
    {% endfor %}
    {% endif %}
    <tr>
        <td colspan="4">
            Receipt Total
        </td>
        <td>
            {{ receipt_total }}
        </td>
    </tr>
</table>

flaskr/templates/receipt/update.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Document</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
    <div class="flash">
        {{ message }}
    </div>
    {% endfor %}
    
</body>
</html>
<div class="main-container">
    <div class="receipt">
            <div class="client-info">
            {% include 'receipt/customer-info.html' %}
            </div>
        <div class="receipt-product">
            {% include 'receipt/products.html' %}
        </div>
    </div>
    <div >
        <a href="{{ url_for('home.home') }}">Home</a>
    </div>

</div>