flaskr/models/customer.py
from sqlalchemy import (
    Column, Integer, String
)
from . import db, commit_to_db


class Customer(db.Model): 
    id = Column(Integer, primary_key=True)
    name = Column(String(100), unique=True, nullable=False)
    address = Column(String(150), unique=True, nullable=False)
    email = Column(String(50), unique=True, nullable=False)

    def add(self):
        db.session.add(self)
        commit_to_db()
    
    def update(self):
        commit_to_db()
    
    def delete(self):
        db.session.delete(self)
        commit_to_db()

    def get(id):
        return Customer.query.get(id)

    def get_all():
        return Customer.query.all()
    
    def search(search_term):
        customer = Customer.query.filter_by(name=search_term)
        if customer is None:
            customer = Customer.query.filter_by(email=search_term)
        if customer is None:
            customer = Customer.query.filter_by(address=search_term)
        
        return customer
    


        

flaskr/models/customer/__init__.py
from sqlalchemy import (
    Column, Integer, String
)
from flaskr.models import db, MyModel


class Customer(db.Model, MyModel): 
    id = Column(Integer, primary_key=True)
    name = Column(String(100), unique=True, nullable=False)
    address = Column(String(150), unique=True, nullable=False)
    email = Column(String(50), unique=True, nullable=False)
    receipts = db.relationship(
        'Receipt',
        backref='author',
        lazy=True,
        cascade="all, delete-orphan"
    )

    def get(id):
        return Customer.query.get(id)

    def get_all():
        return Customer.query.all()
    
    def search(search_term):
        customer = Customer.query.filter_by(name=search_term).first()
        if customer is None:
            customer = Customer.query.filter_by(email=search_term).first()
        if customer is None:
            customer = Customer.query.filter_by(address=search_term).first()
        
        return customer
    
    @property
    def request(self):
        from .request import CustomerRequest
        return CustomerRequest(self)
    


        

flaskr/views/customer.py
from flask import (
    Blueprint, render_template, request, url_for, 
    redirect, flash
)
from flaskr.models.customer import Customer
from . import get_form
bp = Blueprint("customer", __name__, url_prefix='/customer')


customer_heads = {
    'name': "name",
    'address': 'address',
    'email': 'email'
}

@bp.route('/customers')
def customers():
    customers = Customer.get_all()
    
    return render_template(
        "customer/customers.html",
        customers=customers,
        heads=customer_heads
    )


@bp.route('/add', methods=('GET', 'POST'))
def add():
    form = get_form(customer_heads)
    if request.method == "POST":
        customer = Customer(
            name=form["name"],
            address=form["address"],
            email=form['email']
        )
        error = customer.request.add()
        if not error:
            return redirect(
                url_for('customer.customers')
            )
        flash(error)

    return render_template(
        'customer/add.html',
        customer_heads=customer_heads,
        form=form
    )



@bp.route('/update/<int:customer_id>', methods=('GET', 'POST'))
def update(customer_id):
    customer = Customer.get(customer_id)

    if request.method == 'POST':
        error = customer.request.update()
        if not error:
            return redirect(
                url_for('customer.customers')
            )
        flash(error)

    return render_template(
        'customer/update.html',
        heads=customer_heads, 
        customer=customer
    )


@bp.route('/delete/<int:customer_id>')
def delete(customer_id):
    customer = Customer.get(customer_id)
    customer.delete()

    return redirect(
        url_for('customer.customers')
    )

flaskr/templates/customer/add-customer.html
{% extends 'base.html' %}

{% block title %}
<h1>Add Customer</h1>
{% endblock %}


{% block content %}
<div class="title-container">
    <h1 class="title">Add Customer</h1>
</div>


<form method="post" class="add">
{% for customer_head in customer_heads %}
{% if customer_head != 'id'%}
    <div class="label-div">
        <label for="{{ customer_head }}" class="inpul-label">{{ customer_head }}</label>
    </div>
    <div class="input-div">
        <input name="{{ customer_head }}" class="input-customer">
    </div>
{% endif %}
{% endfor %}
<input type="submit" class="submit-btn">
</form>

{% endblock %}

flaskr/templates/customer/add.html
{% extends 'base.html' %}

{% block title %}
<h1>Add Customer</h1>
{% endblock %}


{% block content %}
<div class="title-container">
    <h1 class="title">Add Customer</h1>
</div>


<form method="post" class="add">
{% for head in customer_heads %}
<div class="label-div">
    <label for="{{ head }}" class="inpul-label">{{ head }}</label>
</div>
<div class="input-div">
    <input name="{{ head }}" class="input-customer" value="{{ form[head] }}">
</div>
{% endfor %}
<input type="submit" class="submit-btn">
</form>

{% endblock %}

flaskr/templates/customer/customers.html
{% extends 'base.html' %}

{% block title %}
<h1>Customers</h1>
{% endblock %}

{% block content %}
<div class="title-container">
    <h1 class="title">Customers</h1> 
</div>


<table class="customers">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>e-mail</th>
      </tr>
    {% for customer in customers %}
    <tr>
        {% for head in heads %}
        <td>
            {{ customer[head] }}
        </td>
        {% endfor %}
        <td>
            <a href="{{ url_for('customer.delete', customer_id=customer.id) }}">❌</a>
            <br>
            <a href="{{ url_for('customer.update', customer_id=customer.id) }}">Update</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

flaskr/templates/customer/update.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
    <h1 class="title">Update Client</h1>
</div>

<form method="post" class="update">
    {% for head in heads %}
    {% if heads != id %}
    <div class="label-div">
        <label for="{{ head }}" class="input-label">{{ head }}</label>
    </div>
    <div class="input-div">
        <input type="text" value="{{ customer[head] }}" name="{{ head }}" id="{{ head }}" class="input-customer">
    </div>
    {% endif %}
    {% endfor %}
        <input type="submit" class="submit-btn">
</form>


{% endblock %}