flaskr/views/customer.py
from flask import (
    Blueprint, render_template, request, url_for, 
    redirect, flash
)
from flaskr.models.customer import Customer
from . import get_form
bp = Blueprint("customer", __name__, url_prefix='/customer')


customer_heads = {
    'name': "name",
    'address': 'address',
    'email': 'email'
}

@bp.route('/customers')
def customers():
    customers = Customer.get_all()
    
    return render_template(
        "customer/customers.html",
        customers=customers,
        heads=customer_heads
    )


@bp.route('/add', methods=('GET', 'POST'))
def add():
    form = get_form(customer_heads)
    if request.method == "POST":
        customer = Customer(
            name=form["name"],
            address=form["address"],
            email=form['email']
        )
        error = customer.request.add()
        if not error:
            return redirect(
                url_for('customer.customers')
            )
        flash(error)

    return render_template(
        'customer/add.html',
        customer_heads=customer_heads,
        form=form
    )



@bp.route('/update/<int:customer_id>', methods=('GET', 'POST'))
def update(customer_id):
    customer = Customer.get(customer_id)

    if request.method == 'POST':
        error = customer.request.update()
        if not error:
            return redirect(
                url_for('customer.customers')
            )
        flash(error)

    return render_template(
        'customer/update.html',
        heads=customer_heads, 
        customer=customer
    )


@bp.route('/delete/<int:customer_id>')
def delete(customer_id):
    customer = Customer.get(customer_id)
    customer.delete()

    return redirect(
        url_for('customer.customers')
    )

flaskr/views/product.py
from flask import (
    Blueprint, render_template, request, 
    redirect, url_for, flash
)
from flaskr.models.product import Product 
from . import get_form
bp = Blueprint('product', __name__, url_prefix='/product')


product_heads = {
    'name': 'name',
    'description': 'description',
    'price': 'price',
}


@bp.route('/products')
def products():
    products = Product.get_all()

    return render_template(
        'product/products.html',
        products=products,
        heads=product_heads
    )


@bp.route('/add', methods=("GET", "POST"))
def add():
    form = get_form(product_heads)
    if request.method == "POST":
        product = Product(
            name=form["name"],
            description=form["description"],
            price=form['price']
        )
        error = product.request.add()
        if not error: 
            return redirect(
                url_for('product.products')
            )
        flash(error)

    return render_template(
        'product/add.html',
        product_heads=product_heads
    )


@bp.route('/update/<int:product_id>', methods=("GET", "POST"))
def update(product_id):
    product = Product.get(product_id)
    if request.method == 'POST':
        error = product.request.update()
        if not error:
            return redirect(
                url_for('product.products')
            )

        flash(error)

    return render_template(
        'product/update.html',
        product=product, 
        heads=product_heads
    )


@bp.route('/delete/<int:product_id>', methods=("GET", "POST"))
def delete(product_id):
    product = Product.get(product_id)
    product.delete()

    return redirect(url_for('product.products'))




    

flaskr/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<nav>
    <div >
        <a href="{{ url_for('customer.add') }}">Add Customer</a>
    </div>
    <div>
        <a href="{{ url_for('customer.customers') }}">Customers</a>
    </div>
    <div >
        <a href="{{ url_for('product.add') }}">Add Product</a>
    </div>
    <div>
        <a href="{{ url_for('product.products') }}">Products</a>
    </div>
    <div>
        <a href="{{ url_for('receipt.add') }}">Add Receipt</a>
    </div>
    <div>
        <a href="{{ url_for('receipt.receipts') }}">Receipts</a>
    </div>
   
</nav>
<body>
    {% for message in get_flashed_messages() %}
    <div class="flash">
        {{ message }}
    </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
</body>
</html>