flaskr/models/product.py
from sqlalchemy import (
    Column, Integer, String, 
    Text, Float
)
from . import db, commit_to_db


class Product(db.Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text(1000), nullable=False)
    price = Column(Float, nullable=False, default=0)

    def add(self):
        db.session.add(self)
        commit_to_db()

    def update(self):
        commit_to_db()
    
    def delete(self):
        db.session.delete(self)
        commit_to_db()
    
    def search(search_term):
       return Product.query.filter_by(name=search_term)
       
    def get(id):
        return Product.query.get(id)
    
    def get_all():
        return Product.query.all()

    

flaskr/models/product/__init__.py
from sqlalchemy import (
    Column, Integer, String, 
    Text, Float
)
from flaskr.models import db, MyModel


class Product(db.Model, MyModel):
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text(1000), nullable=False)
    price = Column(Float, nullable=False, default=0)
    sold_products = db.relationship(
        'SoldProduct',
        backref='product',
        lazy=True, 
        cascade='all, delete-orphan'
    )
    
    def search(search_term):
        return Product.query.filter_by(name=search_term).first()
       
    def get(id):
        return Product.query.get(id)
    
    def get_all():
        return Product.query.all()

    @property
    def request(self):
        from .request import ProductRequest
        return ProductRequest(self)

flaskr/views/product.py
from flask import (
    Blueprint, render_template, request, 
    redirect, url_for, flash
)
from flaskr.models.product import Product 
from . import get_form
bp = Blueprint('product', __name__, url_prefix='/product')


product_heads = {
    'name': 'name',
    'description': 'description',
    'price': 'price',
}


@bp.route('/products')
def products():
    products = Product.get_all()

    return render_template(
        'product/products.html',
        products=products,
        heads=product_heads
    )


@bp.route('/add', methods=("GET", "POST"))
def add():
    form = get_form(product_heads)
    if request.method == "POST":
        product = Product(
            name=form["name"],
            description=form["description"],
            price=form['price']
        )
        error = product.request.add()
        if not error: 
            return redirect(
                url_for('product.products')
            )
        flash(error)

    return render_template(
        'product/add.html',
        product_heads=product_heads
    )


@bp.route('/update/<int:product_id>', methods=("GET", "POST"))
def update(product_id):
    product = Product.get(product_id)
    if request.method == 'POST':
        error = product.request.update()
        if not error:
            return redirect(
                url_for('product.products')
            )

        flash(error)

    return render_template(
        'product/update.html',
        product=product, 
        heads=product_heads
    )


@bp.route('/delete/<int:product_id>', methods=("GET", "POST"))
def delete(product_id):
    product = Product.get(product_id)
    product.delete()

    return redirect(url_for('product.products'))




    

flaskr/templates/product/add.html
{% extends 'base.html' %}

{% block title %}
<h1>Add Product</h1>
{% endblock %}


{% block content %}
<div class="title-container">
    <h1 class="title">Add Product</h1>
</div>


<form method="post" class="add">
{% for product_head in product_heads %}
{% if product_head != 'id'%}
    <div class="label-div">
        <label for="{{ product_head }}" class="inpul-label">{{ product_head }}</label>
    </div>
    <div class="input-div">
        <input name="{{ product_head }}" class="input-product">
    </div>
{% endif %}
{% endfor %}
<input type="submit" class="submit-btn">
</form>

{% endblock %}

flaskr/templates/product/products.html
{% extends 'base.html' %}

{% block title %}
<h1>Products</h1>
{% endblock %}

{% block content %}
<div class="title-container">
    <h1 class="title">Products</h1>
</div>
<table class="products">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
      </tr>
    {% for product in products %}
    <tr>
        {% for head in heads %}
        <td>
            {{ product[head] }}
        </td>
        {% endfor %}
        <td>
            <a href="{{ url_for('product.delete', product_id=product.id) }}">❌</a>
            <br>
            <a href="{{ url_for('product.update', product_id=product.id) }}">Update</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

flaskr/templates/product/update.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
    <h1 class="title">Update Product</h1>
</div>


<form method="post" class="update" >
    {% for head in heads %}
    {% if heads != id %}
    <div class="label-div">
        <label for="{{ head }}" class="input-label">{{ head }}</label>
    </div>
    <div class="input-div">
        <input type="text" value="{{ product[head] }}" name="{{ head }}" id="{{ head }}" class="input-product">
    </div>
    {% endif %}
    {% endfor %}
        <input type="submit" class="submit-btn">
</form>


{% endblock %}